# Generated by Django 4.1 on 2022-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
